site_name: Trezarcoin
site_url: https://trezarcoin.com
site_description: Project documentation with Markdown.
site_author: TrezarCr3w

repo_url: https://github.com/peschu123/trezardocs
edit_uri: ""

nav:
    - Home: README.md
    - User Guides:
        - PoW Mining: 00_pow_pool_mining.md
        - PoW & PoS Basics: 10_pow_pos_basics.md
